### ISSUE TITLE
about paper source

### ISSUE THREAD

**Issue by FangGet** [NetEaseAI-CVLab/CNN-MonoFusion#2]
Thanks for opensourcing your code for CNN-MonoFusion , I wonder if it's convenient for you to provide a link for paper source, like arXiv or something else, we can never find detail for that.
Thank you!

**Comment by JackHenry1992** [comment]
I'm very sorry that I have not uploaded our paper to arXiv right now. 
If the paper is published public, I will let you know here

**Comment by FangGet** [comment]
Got it!
