### ISSUE TITLE
The code released is not completely

### ISSUE THREAD

**Issue by AI-slam** [NetEaseAI-CVLab/CNN-MonoFusion#4]
Thanks for your work, I find some code is missing, could you implement it.
in rgbd_monodepth.cc, SLAM.densemap_frame_enqueue() and SLAM.densemap_request_finish() are defined in System.h, but you didn't provide the orb-slam2 source code that you modified for us.  Thanks!

**Comment by JackHenry1992** [comment]
We use the ORBSLAM as the pose calculator and only a little modification of the interface.
It's not suitable for us to provide the orb-slam2 code due to the ORBSLAM own license.

**Comment by ryohachiuma** [comment]
Hi @JackHenry1992, could you at least provide the information what kind of function ``` densemap_frame_enqueue, densemap_request_finish``` is?
Thank you for consideration in advance!

**Comment by JackHenry1992** [comment]
Please refer [densemap.cc](https://github.com/NetEaseAI-CVLab/CNN-MonoFusion/blob/master/pointcloud-fusion/src/dense_map/DenseMap.cc) for pointcloud-fusion code. And [DepthPredictor.cc](https://github.com/NetEaseAI-CVLab/CNN-MonoFusion/blob/master/pointcloud-fusion/src/dense_map/DepthPredictor.cc) is used for manager pointcloud-fusion thread,  all you need will be found in this file.

**Comment by JackHenry1992** [comment]
Furthermore, [dense_map](https://github.com/NetEaseAI-CVLab/CNN-MonoFusion/tree/master/pointcloud-fusion/src/dense_map) is used for the fusion phase.
