### ISSUE TITLE
The use of kinect

### ISSUE THREAD

**Issue by hlzz** [NetEaseAI-CVLab/CNN-MonoFusion#5]
First of all, congratulations on your ISMAR paper! And thanks for making parts of your code open-sourced, although it is not compil-able, for the orb-slam part >:) And the technical choice seems quite right, e.g. the depth module is fused into pose estimation using socket as the bridge. Unfortunately, I can't get access to the paper, so I can only guess your intention so correct me if I am wrong. Specifically, I have two questions:

1) Why do we need kinect here? I thought the cnn-based depth estimator is responsible for depths.

2) How do you solve the scale issue when take learned depth into the pipeline?

I'd appreciate it if you can upload a preview version of the paper, as the ISMAR papers are currently not online.

**Comment by JackHenry1992** [comment]
The Kinect is only for the training phase, which brings the absolute depth scale to CNN.
We take the ratio of the focal length (selected one as basic) as part of input during the training phase, and the true scale can be calculated by passing the focal length ratio into the network during
inference phase.
