### ISSUE TITLE
Download pretrained model

### ISSUE THREAD

**Issue by EnricoBeltramo** [NetEaseAI-CVLab/CNN-MonoFusion#6]
It's difficult to download pretrained model from Baidu for not Chinese native people, it's possible to share them i'.e on Goggle drive or other sharing platforms?

Thank you

**Comment by firebrain7** [comment]
It might help that you can use chrome browser to understand Baidu through google webpage translate.

**Comment by EnricoBeltramo** [comment]
Unfortunately the google translate looks don't be able to translate well the page and for registration ask a Chinese phone number.

**Comment by JackHenry1992** [comment]
Sorry, it's hard to upload our dataset to Google Drive in China... Google is not so friendly for us ...

**Comment by FangGet** [comment]
@JackHenry1992 it's possible for you to upload a zip file instead of dirrectories to Baidu cloud? Just not so convenient for no SuperVIP Baidu user to download directories, -，-

**Comment by ryohachiuma** [comment]
Hi, is it possible to access Microsoft OneDrive from China?
If so, it would be nice to upload to OneDrive instead of Baidu Drive. 
Thank you.
