### ISSUE TITLE
关于深度图的精度和融合

### ISSUE THREAD

**Issue by zebrajack** [NetEaseAI-CVLab/CNN-MonoFusion#7]
王/汪工，

你好。

1. 深度的估算里结合多任务学习，能否提高其精度呀？比如加上normal map和segementation. 最近一篇文章评判了一下DL单目深度的问题 https://mp.weixin.qq.com/s/Er98V1XVzcaEMDxXAO3JFA ， 假如是classification,那我们的样本数据要多大才能说是满足精度的要求呢？
2.pointfusion里面有涉及到uncertainty，谈到这是depth sensor的uncertainty. 这是不是说我们也学习到了这种uncertainty? 但是像CNN-SLAM是直接去算uncertainty.
3. 能知道你私人联系方式吗，希望能得到你的帮助和指教（论文的邮箱发过去，被退回）。

**Comment by JackHenry1992** [comment]
1）Yes， by introducing traditional loss-function，such as optical-flow， or segmentation method as the auxiliary-loss. Depth-estimation relies heavily on various scenes, you can capture a lot of dataset about scenes.
2）Uncertainty, which means confidence about point-cloud, can be used to evaluate the precision of 3D point cloud. We can get high-quality point-cloud by estimating the uncertainty.

**Comment by JackHenry1992** [comment]
We can get high-quality point-cloud by estimating the uncertainty
