### ISSUE TITLE
 mpOrbSlamMap->getKeyframeByframeId(ref_keyframe.frame_idx);?

### ISSUE THREAD

**Issue by prograguo** [NetEaseAI-CVLab/CNN-MonoFusion#9]
thanks for you great work !
but i meet this error
ORB_SLAM2/src/dense_map/DepthPredictor.cc:124:65: error: ‘class ORB_SLAM2::Map’ has no member named ‘getKeyframeByframeId’
                 ORB_SLAM2::KeyFrame *orbslam_kf = mpOrbSlamMap->getKeyframeByframeId(ref_keyframe.frame_idx);
                                                                 ^~~~~~~~~~~~~~~~~~~~

Can you help me solve it?

**Comment by JackHenry1992** [comment]
Oh, sorry for the late reply, you can add a function to map class, which can get keyframe by frame_idx.
